W-11492717: Polling Source notifications Improvements
mulesoft/mule-api pull request #1020
Opened 2022-08-10 13:24 UTC by SebaElizalde

2022-08-11 13:47 UTC, SebaElizalde commented
--validate

2022-08-11 21:08 UTC, ndinu commented on src/main/java/org/mule/runtime/api/notification/PollingSourceItemNotification.java
> +  private String eventId;
Given that the eventId only makes sense for the ITEM_DISPATCHED notification, shouldn't it have its own notification type? Or should we just leave it as null for the other cases?

2022-08-16 13:04 UTC, SebaElizalde commented on src/main/java/org/mule/runtime/api/notification/PollingSourceItemNotification.java
> +  private String eventId;
That is a possibility I considered, but I thought in the end the current implementation is better as a new notification for only 1 notification seemed too much. Current way means less classes (also less listeners that the composer team needs to register) and keeps item notifications grouped together, for only the tradeoff of keeping the parameter null for other cases.

2022-08-16 13:12 UTC, marianogonzalez requested changes

2022-08-16 13:12 UTC, marianogonzalez commented on src/main/java/org/mule/runtime/api/notification/PollingSourceItemNotification.java
> +  private Optional<Serializable> watermark;
Bad usage of Optional. Only wrap at the getter level

2022-08-16 13:12 UTC, marianogonzalez commented on src/main/java/org/mule/runtime/api/notification/PollingSourceItemNotification.java
> +public class PollingSourceItemNotification extends AbstractServerNotification {
jdoc

2022-08-16 13:12 UTC, marianogonzalez commented on src/main/java/org/mule/runtime/api/notification/PollingSourceItemNotification.java
> +  public void setEventId(String eventId) {
shouldn't be mutable

2022-08-16 13:12 UTC, marianogonzalez commented on src/main/java/org/mule/runtime/api/notification/PollingSourceItemNotification.java
> +  private String eventId;
agree with Nico that null handling should be avoided. This should either be splitted or at the very least use an `Optional` for `getEventId()`. The argument of that increasing the number of listeners doesn't apply as the listeners are bound to the action id, not the notification class and you can always have a base class/interface for polling notifications

2022-08-16 19:04 UTC, SebaElizalde commented on src/main/java/org/mule/runtime/api/notification/PollingSourceItemNotification.java
> +  private String eventId;
alright, moved to an Optional

2022-08-17 13:21 UTC, SebaElizalde commented on src/main/java/org/mule/runtime/api/notification/PollingSourceItemNotification.java
> +  public void setEventId(String eventId) {
this is needed to later on set the event Id on the notification (see the other PR):
`template.getSourceMessage().getNotification().ifPresent(n -> {
        ((PollingSourceItemNotification) n).setEventId(event.getContext().getId());`

Alternatively, I can propagate the information needed through a Map<String, String> and create the notification at the FlowProcessMediator

2022-08-17 14:34 UTC, marianogonzalez commented on src/main/java/org/mule/runtime/api/notification/PollingSourceItemNotification.java
> +  public void setEventId(String eventId) {
Not sure I follow the Map part, but the snippet in which you're using this is marked as a no-go in the other PR, so removing that code should also reflect here.

2022-08-17 16:24 UTC, marianogonzalez requested changes

2022-08-17 16:24 UTC, marianogonzalez commented on src/main/java/org/mule/runtime/api/notification/PollingSourceItemNotification.java
> +    return of(watermark);
why not `ofNullable`?

2022-08-17 16:24 UTC, marianogonzalez commented on src/main/java/org/mule/runtime/api/notification/PollingSourceItemNotification.java
> +    return of(eventId);
why not `ofNullable`?

2022-08-17 16:24 UTC, marianogonzalez commented on src/main/java/org/mule/runtime/api/notification/PollingSourceItemNotification.java
> +  public void setEventId(String eventId) {
still not removed

2022-08-22 13:54 UTC, marianogonzalez requested changes

2022-08-22 13:54 UTC, marianogonzalez commented on src/main/java/org/mule/runtime/api/notification/PollingSourceItemNotification.java
> +  public PollingSourceItemNotification(String pollId, String itemId, Serializable watermark, int action,
action should be the first argument

2022-08-22 14:14 UTC, marianogonzalez requested changes

2022-08-22 14:14 UTC, marianogonzalez commented on src/main/java/org/mule/runtime/api/notification/PollingSourceItemNotification.java
> +  private String pollId;
these should all be final

2022-08-24 15:00 UTC, marianogonzalez approved these changes

2022-08-24 16:49 UTC, merged