W-11493163: Add an API for expression validation
mulesoft/mule-api pull request #1050
Opened 2022-10-27 20:00 UTC by mlischetti

2022-10-28 12:55 UTC, mbuchwald approved these changes

2022-10-28 12:58 UTC, elrodro83 requested changes

2022-10-28 12:58 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/el/ExpressionLanguage.java
> +   * @param name     The name of the resource
what is a resource in this context?

2022-10-28 12:58 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/el/ExpressionLanguage.java
> +    public ValidationNotification(String kind, String message, Map<String, String> params,
instead of putting this concrete class in the API with the constructor, maybe only declare the interface as part of the api?

2022-10-28 12:58 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/el/ExpressionLanguage.java
> +  default void validate(String script, String name, TypeBindings bindings, ValidationListener listener) {
add `@since`

2022-10-28 14:07 UTC, mlischetti commented on src/main/java/org/mule/runtime/api/el/ExpressionLanguage.java
> +  default void validate(String script, String name, TypeBindings bindings, ValidationListener listener) {
done!

2022-10-28 14:10 UTC, mlischetti commented on src/main/java/org/mule/runtime/api/el/ExpressionLanguage.java
> +    public ValidationNotification(String kind, String message, Map<String, String> params,
done

2022-10-28 14:24 UTC, elrodro83 requested changes

2022-10-28 14:24 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/el/ExpressionLanguage.java
> +   * @param name     The name of the script to validate
what is the name needed for?

2022-10-28 14:24 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/el/ExpressionLanguage.java
> +  ScopeValidationResult validateScope(String script, String name, TypeBindings bindings);
scope?

2022-10-28 14:24 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/el/validation/DefaultScopeValidationResult.java
> +public class DefaultScopeValidationResult implements ScopeValidationResult {
scope?

2022-10-28 14:24 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/el/validation/DefaultScopeValidationResult.java
> +package org.mule.runtime.api.el.validation;
this should be internal, not api

2022-10-28 14:24 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/el/validation/ScopeValidationResult.java
> +public interface ScopeValidationResult {
scope?

2022-10-28 14:24 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/el/validation/ValidationNotification.java
> +public class ValidationNotification {
this is not a Notification, mybe a validation element, result item?

2022-10-28 18:23 UTC, elrodro83 requested changes

2022-10-28 18:23 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/el/ExpressionLanguage.java
> +   *                       given script.
What if the issue is in a dependency? is it filtered out? how do i identify it?

2022-10-28 18:23 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/el/ExpressionLanguage.java
> +   * @param bindings       The script bindings
add an exampole of how to create this

2022-10-28 18:23 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/el/validation/ScopePhaseValidationItem.java
> +public final class ScopePhaseValidationItem {
wasn't this going to be provate?

2022-10-28 18:32 UTC, mlischetti commented on src/main/java/org/mule/runtime/api/el/ExpressionLanguage.java
> +   *                       given script.
If the issue is in a dependency will be filtered. You will only get errors on your script, not in the dependencies

2022-10-28 19:54 UTC, elrodro83 requested changes

2022-10-28 19:54 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/el/validation/ScopePhaseValidationItem.java
> +  Location getLocation();
add javadocs

2022-10-31 16:11 UTC, elrodro83 requested changes

2022-10-31 16:11 UTC, elrodro83 commented on api-changes.json
> +        },
remove

2022-10-31 16:11 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/el/ExpressionLanguage.java
> +   * @param nameIdentifier The name identifier of the script to validate. It's used to filter the validation messages and to build
still not clear what `It's used to filter` means here.

2022-11-01 12:22 UTC, elrodro83 approved these changes

2022-11-01 12:26 UTC, merged