W-11529823: Idempotent Validation Filter does not cascade object store exception
mulesoft/mule-api pull request #1064
Opened 2022-11-25 15:44 UTC by marianorean

2022-11-25 16:57 UTC, elrodro83 requested changes

2022-11-25 16:57 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/config/MuleRuntimeFeature.java
> +   * When enabled, internal exceptions when processing an event in the IdempotentMessageValidator will be rethrown instead of
mention the component as it is in the dsl instead of the internal classname.

2022-11-25 16:57 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/config/MuleRuntimeFeature.java
> +   * When enabled, internal exceptions when processing an event in the IdempotentMessageValidator will be rethrown instead of
wrap the component name in single quotes

2022-11-25 16:57 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/config/MuleRuntimeFeature.java
> +   * When enabled, internal exceptions when processing an event in the IdempotentMessageValidator will be rethrown instead of
should this mention that this applies only to object store exceptions?

2022-11-25 16:57 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/config/MuleRuntimeFeature.java
> +   * throwing a general DuplicateMessageException.
throwing -> raising

2022-11-25 16:57 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/config/MuleRuntimeFeature.java
> +   * throwing a general DuplicateMessageException.
general DuplicateMessageException -> use the error type the user would see

2022-11-25 16:57 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/util/MuleSystemProperties.java
> +  public static final String RETHROW_EXCEPTIONS_IN_IDEMPOTENT_MESSAGE_VALIDATOR_PROPERTY =
same as in the feature

2022-11-28 13:08 UTC, marianorean commented on src/main/java/org/mule/runtime/api/config/MuleRuntimeFeature.java
> +   * When enabled, internal exceptions when processing an event in the IdempotentMessageValidator will be rethrown instead of
It also rethrows the runtime exceptions

2022-11-28 13:32 UTC, elrodro83 requested changes

2022-11-28 13:32 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/config/MuleRuntimeFeature.java
> +   * raising a general MULE:DUPLICATE_MESSAGE.
put `MULE:DUPLICATE_MESSAGE` as a link to the definition of that error code.

2022-11-28 13:32 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/util/MuleSystemProperties.java
> +   * throwing a general MULE:DUPLICATE_MESSAGE.
put `MULE:DUPLICATE_MESSAGE` as a link to the definition of that error code.

2022-11-29 21:04 UTC, elrodro83 approved these changes

2022-11-30 13:05 UTC, merged