W-12271802: Add Min Mule Version information to the Extension Model
mulesoft/mule-api pull request #1098
Opened 2023-01-18 19:03 UTC by ndinu

2023-01-19 17:57 UTC, marianogonzalez requested changes

2023-01-19 17:57 UTC, marianogonzalez commented on src/main/java/org/mule/runtime/api/meta/model/declaration/fluent/ConfigurationDeclaration.java
> +  public Optional<MuleVersion> getMinMuleVersion() {
I think this can be put higher up in the hierarchy. All these classes extend `ParameterizedDeclaration`, which also extends `NamedDeclaration`. I would create an intermediate one which implements the `WithMinMuleVersionDeclaration` interface and has these methods. Same applies to similar classes in the PR

2023-01-19 17:57 UTC, marianogonzalez commented on src/main/java/org/mule/runtime/api/meta/model/declaration/fluent/HasMinMuleVersionDeclarer.java
> +   * Use this method to specify a {@link MuleVersion} which is the minimum mule version required for the usage of the declarer
`a {@link MuleVersion} which is the minimum mule version required` -> `a {@link MuleVersion} which is the minimum required`

2023-01-19 17:57 UTC, marianogonzalez commented on src/main/java/org/mule/runtime/api/meta/model/declaration/fluent/WithMinMuleVersionDeclaration.java
> +   * Use this method to specify a {@link MuleVersion} which is the minimum mule version required for the usage of the declaration
`which is the minimum mule version required` -> `which is the minimum required`

2023-01-19 17:57 UTC, marianogonzalez commented on src/main/java/org/mule/runtime/api/meta/model/declaration/fluent/WithMinMuleVersionDeclaration.java
> +   * @return an {@link Optional} of a {@link MuleVersion} which is the minimum mule version required for the usage of the
`an {@link Optional} {@link MuleVersion} which is the minimum required`

2023-01-19 17:57 UTC, marianogonzalez commented on src/main/java/org/mule/runtime/api/meta/model/version/HasMinMuleVersion.java
> +   * @return an {@link Optional} of a {@link MuleVersion} which is the minimum mule version required for the usage of the model,
`an {@link Optional} {@link MuleVersion} which is the minimum required for the usage of the model`

2023-01-19 18:00 UTC, marianogonzalez requested changes

2023-01-19 18:00 UTC, marianogonzalez commented on src/main/java/org/mule/runtime/api/meta/model/version/HasMinMuleVersion.java
> +  Optional<MuleVersion> getMinMuleVersion();
what if we make it non-optional and always default to 4.1.1?

2023-01-19 18:08 UTC, ndinu commented on src/main/java/org/mule/runtime/api/meta/model/version/HasMinMuleVersion.java
> +  Optional<MuleVersion> getMinMuleVersion();
That is fine by me, having empty() or "4.1.1." would mean the same. If you'd like that more, I am not opposed to the change.

2023-01-25 11:35 UTC, marianogonzalez approved these changes

2023-01-25 12:18 UTC, merged