W-12128703: Add feature flag
mulesoft/mule-api pull request #1106
Opened 2023-01-25 01:15 UTC by hyerans

2023-02-03 19:38 UTC, asanguinetti requested changes
Just some OCD cosmetic changes.

2023-02-03 20:42 UTC, fsgonz requested changes

2023-02-03 20:42 UTC, fsgonz commented on src/main/java/org/mule/runtime/api/config/MuleRuntimeFeature.java
> +      "W-12128703", "4.0.0", USE_TRANSACTION_SINK_INDEX_PROPERTY);
change 4.0.0 to "4.0.0, 4.1.0, 4.2.0, 4.3.0, 4.4.0, 4.5.0"

2023-02-03 20:55 UTC, asanguinetti approved these changes

2023-02-06 21:07 UTC, fsgonz commented
--validate

2023-02-07 02:06 UTC, fsgonz approved these changes

2023-02-07 02:07 UTC, merged