W-14488411: Provide an API for building/querying the registry
mulesoft/mule-api pull request #1251
Opened 2023-11-27 21:11 UTC by rbourbonnavarro

2023-12-12 20:45 UTC, elrodro83 requested changes

2023-12-12 20:45 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/config/custom/CustomizationService.java
> +  interface ServiceInterceptor {
would it be worth to add a generic to force the types of `getDefaultServiceImpl ` and `newServiceImpl ` to be conssitent?

2023-12-12 20:45 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/config/custom/CustomizationService.java
> +     * @return the default service implementation that is going to be overridden.
explain what an empty optional means

2023-12-12 20:45 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/config/custom/CustomizationService.java
> +    void newServiceImpl(Object newServiceImpl);
i think we have already discussed this... but why `new...` instead of `override...`

2023-12-13 19:14 UTC, elrodro83 requested changes

2023-12-13 19:14 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/config/custom/CustomizationService.java
> +  void interceptDefaultServiceImpl(String serviceId, Consumer<ServiceInterceptor> serviceInterceptor);
add the generic to ServiceInterceptor

2023-12-13 20:09 UTC, elrodro83 submitted a review, later dismissed

2023-12-14 15:10 UTC, marianogonzalez requested changes

2023-12-14 15:10 UTC, marianogonzalez commented on src/main/java/org/mule/runtime/api/config/custom/CustomizationService.java
> +   * @since 4.6
1.6

2023-12-14 15:10 UTC, marianogonzalez commented on src/main/java/org/mule/runtime/api/config/custom/CustomizationService.java
> +    void skip();
skip() is confusing. Skip the impl? skip the interception? Isn't remove() much clearer?

2023-12-14 20:19 UTC, marianogonzalez approved these changes

2023-12-14 20:21 UTC, merged