W-15247302: Create simple/usual scope and routers OutputResolvers for usability
mulesoft/mule-api pull request #1308
Opened 2024-03-13 19:58 UTC by mbuchwald

2024-03-13 23:13 UTC, mbuchwald commented
--validate

2024-03-14 00:30 UTC, marianogonzalez requested changes

2024-03-14 00:30 UTC, marianogonzalez commented on src/main/java/org/mule/runtime/api/metadata/resolving/AllOfRoutesOutputTypeResolver.java
> +public class AllOfRoutesOutputTypeResolver implements OutputTypeResolver<Void> {
I don't think these implementations should be API. We need an utils method to get them (probably defined in `mule-core` but open to other idesas) but the impls themselves should ideally be private.

2024-03-14 00:30 UTC, marianogonzalez commented on src/main/java/org/mule/runtime/api/metadata/resolving/AllOfRoutesOutputTypeResolver.java
> +    return "OUTPUT_ROUTER_DYNAMIC";
Not a representative name. That been said, should the category and resolverName be parameterizable? Won't we run into issues otherwise?

2024-03-14 00:30 UTC, marianogonzalez commented on src/main/java/org/mule/runtime/api/metadata/resolving/OneOfRoutesOutputTypeResolver.java
> +    return "OUTPUT_ROUTER_DYNAMIC";
name and category shouldn't mathch with the other resolvers.

2024-03-14 00:30 UTC, marianogonzalez commented on src/main/java/org/mule/runtime/api/metadata/resolving/SameAsChainOutputTypeResolver.java
> +public class SameAsChainOutputTypeResolver implements OutputTypeResolver<Void> {
would rename as passthrough

2024-03-15 14:49 UTC, closed without merging