W-15289109: remove usage of internals from Mule APIs
mulesoft/mule-api pull request #1315
Opened 2024-03-22 19:52 UTC by rbourbonnavarro

2024-03-26 20:11 UTC, elrodro83 requested changes

2024-03-26 20:11 UTC, elrodro83 commented on src/main/java/module-info.java
>        com.mulesoft.anypoint.gw.module.autodiscovery;
make the corresponding change in the gateway

2024-03-27 19:30 UTC, elrodro83 approved these changes

2024-03-27 19:33 UTC, rbourbonnavarro commented
--validate

2024-04-03 13:25 UTC, rbourbonnavarro commented
--validate

2024-04-04 19:47 UTC, rbourbonnavarro commented
--validate

2024-04-05 11:23 UTC, elrodro83 approved these changes

2024-04-05 14:10 UTC, merged