W-15402245: Remove directed exports from `mule-artifact-ast`
mulesoft/mule-api pull request #1334
Opened 2024-04-17 14:07 UTC by rbourbonnavarro

2024-04-17 14:30 UTC, elrodro83 requested changes

2024-04-17 14:30 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/meta/model/DefaultTypeAnnotationModelPropertyWrapper.java
> +public class DefaultTypeAnnotationModelPropertyWrapper implements TypeAnnotationModelPropertyWrapper {
make internal

2024-04-18 02:19 UTC, rbourbonnavarro commented
--validate

2024-05-14 16:28 UTC, elrodro83 approved these changes

2024-05-14 16:47 UTC, merged