W-15885175: split container layers in `mule-tests-runner`
mulesoft/mule-api pull request #1359
Opened 2024-06-18 21:19 UTC by rbourbonnavarro

2024-06-19 11:52 UTC, elrodro83 reviewed
Can you do some benchmark on the spi lookup? With this change it will be done every time.
Maybe we should run some perf suite as well.

2024-06-27 13:13 UTC, elrodro83 requested changes

2024-07-01 19:01 UTC, rbourbonnavarro commented on src/main/java/org/mule/runtime/api/util/classloader/MuleImplementationLoaderUtils.java
> +  private static final Map<ClassLoader, ClassLoader> muleImplementationsLoaders = new HashMap();
Might be, changed it.

2024-07-02 16:05 UTC, elrodro83 approved these changes

2024-07-02 18:41 UTC, rbourbonnavarro commented
--validate

2024-07-03 16:28 UTC, merged