W-15676027: Increasing visibility of BaseInputMetadataDescriptor and adding InputChainMetadata to ComponentMetadataTypesDescriptor.
mulesoft/mule-api pull request #1369
Opened 2024-07-01 20:54 UTC by asanguinetti

2024-07-02 16:00 UTC, mbuchwald submitted a review, later dismissed

2024-07-12 19:14 UTC, mbuchwald approved these changes

2024-07-17 13:07 UTC, marianogonzalez requested changes

2024-07-17 13:07 UTC, marianogonzalez commented on src/main/java/module-info.java
> +  exports org.mule.runtime.privileged.metadata;
shouldn't priviledged exports by directed?

2024-07-17 13:07 UTC, marianogonzalez commented on src/main/java/org/mule/runtime/privileged/metadata/InternalMetadataContext.java
> +public interface InternalMetadataContext extends MetadataContext {
add `@NoImplement` and `@Experimienetal` (with the corresponding jdoc disclaimer)

2024-07-17 13:07 UTC, marianogonzalez commented on src/main/java/org/mule/runtime/api/metadata/descriptor/ComponentMetadataTypesDescriptor.java
> +      return this.withInputMetadataDescriptor((BaseInputMetadataDescriptor) inputMetadataDescriptor);
why cast?

2024-07-17 13:07 UTC, marianogonzalez commented on src/main/java/org/mule/runtime/privileged/metadata/InternalMetadataContext.java
> +  Optional<ExpressionLanguageMetadataService> getExpressionLanguageMetadataService();
why obtain this through the context instead of thorugh `@Inject`? or are we missing DI in the resolvers?

2024-07-17 13:07 UTC, marianogonzalez commented on src/main/java/org/mule/runtime/privileged/metadata/InternalMetadataContext.java
> +   * @return the {@link TypeBindings} in context, if available.
not a helpful jdoc. What is this for? what does it contain?

2024-07-17 14:27 UTC, asanguinetti commented on src/main/java/module-info.java
> +  exports org.mule.runtime.privileged.metadata;
I thought so too. But it seems we can't do that anymore because of polymules. Because now the target modules will be in a lower layer, and the API layer will not see them.

2024-07-17 14:27 UTC, asanguinetti commented on src/main/java/org/mule/runtime/api/metadata/descriptor/ComponentMetadataTypesDescriptor.java
> +      return this.withInputMetadataDescriptor((BaseInputMetadataDescriptor) inputMetadataDescriptor);
because otherwise it will call the same method and it will be an infinite recursion.

2024-07-17 14:27 UTC, asanguinetti commented on src/main/java/org/mule/runtime/privileged/metadata/InternalMetadataContext.java
> +   * @return the {@link TypeBindings} in context, if available.
I thought it would be enough by just going to the JDoc of `TypeBindings` to understand that. But I can try to add some more data. As to "what is this for" I'll see what I can put without being over-specific.

2024-07-17 17:42 UTC, asanguinetti commented on src/main/java/org/mule/runtime/privileged/metadata/InternalMetadataContext.java
> +   * @return the {@link TypeBindings} in context, if available.
Improved, let me know what you think.

2024-07-17 18:16 UTC, asanguinetti commented on src/main/java/org/mule/runtime/privileged/metadata/InternalMetadataContext.java
> +  Optional<ExpressionLanguageMetadataService> getExpressionLanguageMetadataService();
We are not injecting the resolvers (checked empirically). Maybe it is possible to add that, but I wouldn’t like to add it to this task's scope.

2024-07-19 10:59 UTC, marianogonzalez submitted a review, later dismissed

2024-07-19 14:59 UTC, marianogonzalez submitted a review, later dismissed

2024-07-19 16:06 UTC, marianogonzalez approved these changes

2024-07-19 22:14 UTC, merged