W-16497173: EL Validation API
mulesoft/mule-api pull request #1399
Opened 2024-08-14 17:17 UTC by gsfernandes

2024-09-19 21:20 UTC, elrodro83 requested changes

2024-09-19 21:20 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/el/ExpressionLanguage.java
> +   */
add `@since 1.9`

2024-09-19 21:20 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/el/validation/ConstraintViolation.java
> +  static ConstraintViolation warning(String kind, String message, Location location) {
is this ok as part of the api? shouldn't this be in the impl?

2024-09-19 21:20 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/el/validation/ConstraintViolation.java
> +  static ConstraintViolation error(String kind, String message, Location location) {
is this ok as part of the api? shouldn't this be in the impl?

2024-09-19 21:20 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/el/validation/ScopePhaseValidationItem.java
> + * @deprecated since 1.9.0.
link to the replacement

2024-09-19 21:20 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/el/validation/ScopePhaseValidationItemKind.java
> + * @deprecated since 1.9.0.
replacement

2024-09-19 21:20 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/el/validation/ScopePhaseValidationMessages.java
> + * @deprecated since 1.9.0.
replacement

2024-09-19 21:22 UTC, gsfernandes commented on src/main/java/org/mule/runtime/api/el/validation/ConstraintViolation.java
> +  static ConstraintViolation warning(String kind, String message, Location location) {
Not it is not. It makes sense to move this to the implementation part. I will change it.

2024-09-19 21:23 UTC, gsfernandes commented on src/main/java/org/mule/runtime/api/el/validation/ConstraintViolation.java
> +  static ConstraintViolation error(String kind, String message, Location location) {
Same as warning, I'll move this to implementation.

2024-09-20 11:29 UTC, elrodro83 approved these changes

2024-09-20 13:07 UTC, elrodro83 approved these changes

2024-09-20 13:20 UTC, elrodro83 approved these changes

2024-09-20 16:35 UTC, merged