W-16584126: allow configuring repeated server actions
mulesoft/mule-api pull request #1431
Opened 2024-09-03 15:08 UTC by rbourbonnavarro

2024-09-04 20:29 UTC, elrodro83 approved these changes

2024-09-05 00:37 UTC, rbourbonnavarro commented
--validate

2024-09-05 15:58 UTC, elrodro83 requested changes

2024-09-05 15:58 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/metadata/DataType.java
> +    private transient final Map<ClassLoader, DataType> cache = new ConcurrentHashMap<>();
nullCheck, cache will be null after deserialization

2024-09-05 21:04 UTC, elrodro83 approved these changes

2024-09-06 12:35 UTC, merged