W-16678830: Update jakarta dependencies in soap-service and http-service
mulesoft/mule-api pull request #1453
Opened 2024-10-15 21:29 UTC by marianorean

2024-12-04 11:51 UTC, elrodro83 requested changes

2024-12-04 11:51 UTC, elrodro83 commented on src/test/resources/media_type/MediaTypeV10.class
why is this regenerated? what was thistesting?

2024-12-04 13:36 UTC, marianorean commented on src/test/resources/media_type/MediaTypeV10.class
It seems to be testing some kind of serialization compatibility of the class MediaType between V11 (has some attribute added) and version V10. 

From the readme: This contains file needed to test serialization of MediaType across different versions of the code.

I had to regenerate the class for compatibility of the change of javax to jakarta so it can be loaded [here](https://github.com/mulesoft/mule-api/blob/546ac448c58bbe6cc38f2dc357922cbd50a4627c/src/test/java/org/mule/runtime/api/test/metadata/MediaTypeSerializationVersionsTestCase.java#L64.)

2024-12-04 21:23 UTC, elrodro83 requested changes

2024-12-04 21:23 UTC, elrodro83 commented on src/test/resources/media_type/MediaTypeV10.class
does this mean that objects serialized in previous versions of the runtime won't be able to be deserialized in the new one?

2024-12-05 13:17 UTC, elrodro83 approved these changes

2024-12-07 13:45 UTC, merged