CMTS-29: Sample Data Tooling implementation
mulesoft/mule-api pull request #712
Opened 2020-09-17 16:13 UTC by svacas

2020-09-17 16:41 UTC, gsfernandes commented
All of the service provided by Mule have this contract, a result object. Seems that we didn't think about it when defining the API for the org.mule.runtime.core.api.data.sample.SampleDataService. Should we use this on the service @marianogonzalez?
ValueProvider, Metadata, TestConnectivity all of them define a result as the one proposed here by @svacas.
I would also change this in the service. Do you agree?

2020-09-18 07:50 UTC, lucianoRM requested changes

2020-09-18 07:50 UTC, lucianoRM commented on src/main/java/org/mule/runtime/api/sampledata/ImmutableSampleDataResult.java
> +    return ofNullable(failure);
Avoid creating a new Optional instance every time

2020-09-18 07:50 UTC, lucianoRM commented on src/main/java/org/mule/runtime/api/sampledata/SampleDataResult.java
> +  static SampleDataResult resultFrom(SampleDataFailure failure) {
Maybe rename these static methods?

If statically imported: `resultFrom()` does not provide much information of which result we are talking about. `sampleDataResultFrom()` would be better. 

If not statically imported: `SampleDataResult.resultFrom()` seems redundant.` from()` would be better: `SampleDataResult.from()`.

2020-09-18 13:47 UTC, svacas commented on src/main/java/org/mule/runtime/api/sampledata/ImmutableSampleDataResult.java
> +    return ofNullable(failure);
you mean caching the optional? I don't see that idiom used anywhere, do you have an example?

2020-09-18 13:48 UTC, svacas commented on src/main/java/org/mule/runtime/api/sampledata/SampleDataResult.java
> +  static SampleDataResult resultFrom(SampleDataFailure failure) {
It's consistent with `ValueResult` interface as it is. `MetadataResult` uses `success()` and `failure()` not sure if it's better.

2020-09-18 15:27 UTC, gsfernandes commented on src/main/java/org/mule/runtime/api/sampledata/ImmutableSampleDataResult.java
> +    return ofNullable(failure);
As coded is right, what is a bad practice is to have a field of type Optional. Caching it won't make any difference here.

2020-09-18 15:29 UTC, gsfernandes approved these changes
Just change the PR name and commit message to a Mule ticket instead.

2020-09-18 15:57 UTC, lucianoRM commented on src/main/java/org/mule/runtime/api/sampledata/ImmutableSampleDataResult.java
> +    return ofNullable(failure);
The problem is that Optional does not implement Serializable, but we are not using that API anywhere, so I don't know if that is an issue to us. 
I know that you should only use Optionals as return types, but it seems wrong to create the same instance over and over every time the getter methods are called.

2020-09-18 15:58 UTC, lucianoRM commented on src/main/java/org/mule/runtime/api/sampledata/SampleDataResult.java
> +  static SampleDataResult resultFrom(SampleDataFailure failure) {
You are right. I would love to change all three. But for the sake of consistency lets leave it like this.

2020-09-18 16:00 UTC, svacas commented on src/main/java/org/mule/runtime/api/sampledata/ImmutableSampleDataResult.java
> +    return ofNullable(failure);
if it's null it returns the same empty instance but if not you are right. Not sure if the overhead is significant though.

2020-09-18 18:43 UTC, lucianoRM approved these changes

2020-09-18 19:49 UTC, merged