MULE-18631: Need to be able to set a limit on the number of events to be pushed per poll where N >= 1
mulesoft/mule-api pull request #736
Opened 2020-11-10 16:17 UTC by ndinu

2020-11-10 20:06 UTC, Bardammu commented on src/main/java/org/mule/runtime/api/util/MuleSystemProperties.java
> +   * When present, adds to polling sources the parameter to configure the item limit per poll feature.
I'd say "to configure the number of items per opoll " or something like that, but I'm not Shakespeare

2020-11-10 20:06 UTC, Bardammu submitted a review, later dismissed

2020-11-11 15:36 UTC, SebaElizalde approved these changes

2020-11-11 15:56 UTC, Bardammu approved these changes

2020-11-11 19:49 UTC, marianogonzalez requested changes

2020-11-11 19:49 UTC, marianogonzalez commented on src/main/java/org/mule/runtime/api/util/MuleSystemProperties.java
> +   * When present, adds to polling sources the parameter to configure the maximum number of items per poll to be processed.
`When present, adds to polling sources the parameter to configure` -> `When present, Polling Sources are enriched with a parameter for configuring`

2020-11-12 20:23 UTC, marianogonzalez approved these changes

2020-11-12 21:26 UTC, merged