MULE-18875: ValueProvider/SampleData optional parameters declared in resolver are not included in the model
mulesoft/mule-api pull request #738
Opened 2020-11-11 16:34 UTC by gabrieldalborgo

2020-11-11 19:41 UTC, ndinu commented on src/main/java/org/mule/runtime/api/meta/model/parameter/ValueProviderModel.java
>      return actingParameters;
We should deprecate this method

2020-11-11 19:41 UTC, ndinu commented on src/main/java/org/mule/runtime/api/meta/model/parameter/ValueProviderModel.java
> +  public ValueProviderModel(List<String> actingParameters, List<ParameterModel> parameters, boolean requiresConfiguration,
We must create a new constructor, modifying the existing one breaks the api.

2020-11-11 19:41 UTC, ndinu commented on src/main/java/org/mule/runtime/api/meta/model/parameter/ValueProviderModel.java
> +  public ValueProviderModel(List<String> actingParameters, List<ParameterModel> parameters, boolean requiresConfiguration,
Maybe the new constructor does not need to receive the actingParameters.

2020-11-11 19:44 UTC, ndinu commented on src/main/java/org/mule/runtime/api/meta/model/parameter/ValueProviderModel.java
> +    this(actingParameters, emptyList(), requiresConfiguration, requiresConnection, isOpen, partOrder, providerName, providerName);
keep delegating on the same constructor

2020-11-11 19:59 UTC, gabrieldalborgo commented on src/main/java/org/mule/runtime/api/meta/model/parameter/ValueProviderModel.java
> +  public ValueProviderModel(List<String> actingParameters, List<ParameterModel> parameters, boolean requiresConfiguration,
But this constructor had been shipped in a released version?

2020-11-11 20:09 UTC, ndinu commented on src/main/java/org/mule/runtime/api/meta/model/parameter/ValueProviderModel.java
> +  public ValueProviderModel(List<String> actingParameters, List<ParameterModel> parameters, boolean requiresConfiguration,
Good point, I did not see that it has the @since 1.4.0 there. I still think it is better to create a new one though we would not be breaking semver by changing it.

2020-11-11 20:20 UTC, gabrieldalborgo commented on src/main/java/org/mule/runtime/api/meta/model/parameter/ValueProviderModel.java
> +  public ValueProviderModel(List<String> actingParameters, List<ParameterModel> parameters, boolean requiresConfiguration,
Regarding 'actingParameters', do you think that we must infer them from the list of ParameterModel?
I did not do that because this class has no bussiness logic, and I preferred to keep it at ValueProvidersParameterDeclarationEnricher class.

2020-11-17 16:23 UTC, ndinu commented
LGTM , just needs the sample data part to be added.

2020-11-17 16:28 UTC, gabrieldalborgo commented
> LGTM , just needs the sample data part to be added.

@ndinu  I just added the sample data part.

2020-11-25 18:50 UTC, gabrieldalborgo commented
--validate

2020-11-26 16:21 UTC, marianogonzalez requested changes

2020-11-26 16:21 UTC, marianogonzalez commented on src/main/java/org/mule/runtime/api/meta/model/data/sample/SampleDataProviderModel.java
> +  @Deprecated
this has never been released yet. Just delete it

2020-11-26 16:21 UTC, marianogonzalez commented on src/main/java/org/mule/runtime/api/meta/model/data/sample/SampleDataProviderModel.java
> +    requireNonNull(parameters, "'parameters' can't be null");
be consistent. Use `checkArgument` too

2020-11-26 16:21 UTC, marianogonzalez commented on src/main/java/org/mule/runtime/api/meta/model/data/sample/SampleDataProviderModel.java
> +    this.actingParameters = parameters.stream().filter(ParameterModel::isRequired).map(ParameterModel::getName).collect(toList());
Why do you still need this concept? Optional parameter are also acting, only that optionally. Even if you still need them, this should be done lazily

2020-11-26 16:21 UTC, marianogonzalez commented on src/main/java/org/mule/runtime/api/meta/model/data/sample/SampleDataProviderModel.java
> +  @Deprecated
delete

2020-11-26 16:21 UTC, marianogonzalez commented on src/main/java/org/mule/runtime/api/meta/model/data/sample/SampleDataProviderModel.java
>          .append(actingParameters)
remove

2020-11-26 16:21 UTC, marianogonzalez commented on src/main/java/org/mule/runtime/api/meta/model/data/sample/SampleDataProviderModel.java
>          .append(actingParameters, that.actingParameters)
remove

2020-11-26 16:21 UTC, marianogonzalez commented on src/main/java/org/mule/runtime/api/meta/model/parameter/ValueProviderModel.java
> +    requireNonNull(actingParameters, "'actingParameters' can't be null");
why did you made this changes?

2020-11-26 16:21 UTC, marianogonzalez commented on src/main/java/org/mule/runtime/api/meta/model/parameter/ValueProviderModel.java
> +    this.parameters = emptyList();
This breaches the contract. The class is annotated with `@DoNotInstantiate`. Just delete this

2020-11-26 16:21 UTC, marianogonzalez commented on src/main/java/org/mule/runtime/api/meta/model/parameter/ValueProviderModel.java
> +    this.actingParameters =
do this lazily when and if the old getter is ever invoked.

2020-11-26 16:21 UTC, marianogonzalez commented on src/main/java/org/mule/runtime/api/meta/model/parameter/ValueProviderModel.java
>          .append(actingParameters, that.actingParameters)
remove

2020-11-26 16:21 UTC, marianogonzalez commented on src/main/java/org/mule/runtime/api/meta/model/parameter/ValueProviderModel.java
>          .append(actingParameters)
remove

2020-12-01 15:46 UTC, gabrieldalborgo commented on src/main/java/org/mule/runtime/api/meta/model/parameter/ValueProviderModel.java
> +    this.parameters = emptyList();
What do you mean by removing this? Delete this constructor? It makes sense because the jdocs says 'since 4.4.0' and it's marked as deprecated.

But, what should I do with the original constructor? To maintain backward compatibility, should I create the ActingParameterModel list from the original acting parameter's List (List <String>)?

2020-12-01 15:46 UTC, gabrieldalborgo commented on src/main/java/org/mule/runtime/api/meta/model/parameter/ValueProviderModel.java
> +    requireNonNull(actingParameters, "'actingParameters' can't be null");
Because checkNotNull is deprecated

2020-12-01 17:05 UTC, marianogonzalez requested changes

2020-12-01 17:05 UTC, marianogonzalez commented on src/main/java/org/mule/runtime/api/meta/model/parameter/ValueProviderModel.java
> +    requireNonNull(actingParameters, "'actingParameters' can't be null");
you should use checkArgument instead

2020-12-01 17:05 UTC, marianogonzalez commented on src/main/java/org/mule/runtime/api/meta/model/parameter/ValueProviderModel.java
> +    this.parameters = emptyList();
This breaches the contract because you're adding a way of creating an instance in which there's no correlation between the `getParameters()` and `getActingParameter()`methods. Keeping the old constructor would be ideal, but it's simply not possible.

Since the class is annotated with `@NoInstantiate`, you can remove the constructor without actually breaking backwards since we made it part of this class API that the runtime is the only one allowed to instantiated, so you shouldn't have any big issues with that change

2020-12-02 18:52 UTC, marianogonzalez commented on api-changes.json
> +          "justification": "The class is annotated with @NoInstantiate"
elaborate on this. Explain that keeping this constructor will breach the contract between those two methods

2020-12-02 18:52 UTC, marianogonzalez commented on src/main/java/org/mule/runtime/api/meta/model/data/sample/SampleDataProviderModel.java
> +    this.parameters = parameters;
wrap into an unmodifiableList

2020-12-02 18:52 UTC, marianogonzalez commented on src/main/java/org/mule/runtime/api/meta/model/parameter/ActingParameterModel.java
> + * @since 4.4.0
1.4.0

2020-12-02 18:52 UTC, marianogonzalez commented on src/main/java/org/mule/runtime/api/meta/model/parameter/ValueProviderModel.java
> +    this.actingParameters = parameters.stream().filter(ActingParameterModel::isRequired)
this should be lazy.

2020-12-02 18:52 UTC, marianogonzalez commented on src/main/java/org/mule/runtime/api/meta/model/parameter/ValueProviderModel.java
> +   * @deprecated Use {@link #getParameters()} instead.
specify when it was deprecated

2020-12-02 18:52 UTC, marianogonzalez commented on src/main/java/org/mule/runtime/api/meta/model/parameter/ValueProviderModel.java
> +    this.parameters = parameters;
wrap into `unmodifiableList`

2020-12-02 19:18 UTC, gabrieldalborgo commented on src/main/java/org/mule/runtime/api/meta/model/parameter/ValueProviderModel.java
> +    this.actingParameters = parameters.stream().filter(ActingParameterModel::isRequired)
Doing that causes some tests to fail. Because the serialized extension model will not have the actingParameters, unless you specifically call the getter so that the actingParameters are loaded.

2020-12-02 19:20 UTC, gabrieldalborgo commented on api-changes.json
> +          "justification": "The class is annotated with @NoInstantiate"
Done

2020-12-02 19:20 UTC, gabrieldalborgo commented on src/main/java/org/mule/runtime/api/meta/model/data/sample/SampleDataProviderModel.java
> +    this.parameters = parameters;
Done

2020-12-02 19:20 UTC, gabrieldalborgo commented on src/main/java/org/mule/runtime/api/meta/model/parameter/ActingParameterModel.java
> + * @since 4.4.0
Done

2020-12-02 19:20 UTC, gabrieldalborgo commented on src/main/java/org/mule/runtime/api/meta/model/parameter/ValueProviderModel.java
> +   * @deprecated Use {@link #getParameters()} instead.
Done

2020-12-02 19:21 UTC, gabrieldalborgo commented on src/main/java/org/mule/runtime/api/meta/model/parameter/ValueProviderModel.java
> +    this.parameters = parameters;
Done

2020-12-03 18:39 UTC, marianogonzalez approved these changes

2020-12-17 14:03 UTC, marianogonzalez requested changes

2020-12-17 14:03 UTC, marianogonzalez commented on src/main/java/org/mule/runtime/api/meta/model/parameter/ActingParameterModel.java
> + * An acting parameter of a {@link ValueProviderModel} or {@link SampleDataProviderModel}
An acting parameter of a design time tooling capability, such as VP or SAmple Data... This might eventually be used by other features we're thinking about, or even DataSense itself... We shouldn't have to update the jdoc each time we add a feature

2020-12-17 15:40 UTC, marianogonzalez approved these changes

2020-12-17 21:08 UTC, merged