Feature/mule 18976
mulesoft/mule-api pull request #746
Opened 2020-12-11 00:56 UTC by szaffarano

2020-12-21 18:17 UTC, elrodro83 requested changes

2020-12-21 18:17 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/config/Feature.java
> +  TESTING_FEATURE("Feature used just for testing purposes.");
it is very weird to have this in the api module.

2020-12-22 15:14 UTC, elrodro83 requested changes

2020-12-22 15:14 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/config/Features.java
> +  ;
remove

2020-12-22 15:14 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/config/Feature.java
> +  String getDescription();
add javadoc

2020-12-22 15:14 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/config/Features.java
> +public enum Features implements Feature {
rename to `MuleRuntimeFeature`

2020-12-22 15:14 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/config/Features.java
> + * List of {@link Feature} that can be configured to be enabled or disabled per application depending on the deployment context.
add into this javadoc the format that a feature shuold have when declared in an implementation, so it is documented properly.. For instance, the issue key that motivated it, which version it exists from, etc.

2020-12-22 21:17 UTC, szaffarano commented on src/main/java/org/mule/runtime/api/config/Features.java
> +  ;
The semicolon is needed if the enum hasn't any constant, otherwise this file doesn't compile.

2020-12-23 12:40 UTC, elrodro83 requested changes

2020-12-23 12:40 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/config/Feature.java
> +  String getIssue();
`getIssueId` sounds better

2020-12-23 12:40 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/config/Feature.java
> +   * @return Issue that motivated the feature.
add an example

2020-12-23 12:40 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/config/MuleRuntimeFeature.java
> +  ;
remove this

2020-12-23 13:46 UTC, elrodro83 approved these changes

2020-12-23 15:34 UTC, merged