MULE-19038: feature flag reserved variable names
mulesoft/mule-api pull request #748
Opened 2020-12-23 18:59 UTC by szaffarano

2020-12-23 19:13 UTC, elrodro83 requested changes

2020-12-23 19:13 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/util/MuleSystemProperties.java
> +  public static final String HONOUR_RESERVED_PROPERTIES_PROPERTY = SYSTEM_PROPERTY_PREFIX + "honour.reserved.properties";
overrides should be managed by the feature service internally, in a generic standard way.

2020-12-29 20:56 UTC, szaffarano commented on src/main/java/org/mule/runtime/api/util/MuleSystemProperties.java
> +  public static final String HONOUR_RESERVED_PROPERTIES_PROPERTY = SYSTEM_PROPERTY_PREFIX + "honour.reserved.properties";
I left the System Property constant definition here, but the logic that uses it remains internally to the Feature Flagging mechanism.  Do you think that we should define this constant only [here](https://github.com/mulesoft/mule-api/pull/748/files#diff-9018e4b400b25f6397972e30bf9832135f6557d83869174a7c8a99e87f20f32aR64)?

2020-12-29 21:03 UTC, elrodro83 requested changes

2020-12-29 21:03 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/config/MuleRuntimeFeature.java
> + *      HONOUR_RESERVED_PROPERTIES("Whether reserved properties such as app.name can't be overridden by global properties.",
`app.name` -> `'app.name'`

2020-12-29 21:03 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/config/MuleRuntimeFeature.java
> +  HONOUR_RESERVED_PROPERTIES("Whether reserved properties such as app.name can't be overridden by global properties.",
`app.name` -> `'app.name'`

2020-12-29 21:12 UTC, elrodro83 submitted a review, later dismissed

2021-01-11 13:55 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/util/MuleSystemProperties.java
> +  public static final String HONOUR_RESERVED_PROPERTIES_PROPERTY = SYSTEM_PROPERTY_PREFIX + "honour.reserved.properties";
nah, it's okay to have it here as long as the doc references the proper flag it modifies.

2021-01-11 13:55 UTC, elrodro83 approved these changes

2021-01-11 16:32 UTC, merged