MULE-19041: Support value providers at body level
mulesoft/mule-api pull request #817
Opened 2021-04-21 15:52 UTC by Bardammu

2021-04-22 12:48 UTC, ndinu requested changes

2021-04-22 12:48 UTC, ndinu commented on src/main/java/org/mule/runtime/api/meta/model/declaration/fluent/ParameterDeclaration.java
> +  public List<FieldValueProviderModel> getFieldValueProviderModels() {
It is fine to add these methods, but to keep using the pattern that is being used for creating the Declarations, the declarer must expose how to add these fieldValueProviderModels

2021-04-28 15:34 UTC, marianogonzalez requested changes

2021-04-28 15:34 UTC, marianogonzalez commented on src/main/java/org/mule/runtime/api/meta/model/parameter/FieldValueProviderModel.java
> +public class FieldValueProviderModel extends ValueProviderModel {
Add `@NoInstantiate` and `@NoExtend`

2021-04-28 15:34 UTC, marianogonzalez commented on src/main/java/org/mule/runtime/api/meta/model/parameter/FieldValueProviderModel.java
> +        .isEquals() && super.equals(o);
`super.equals` implementation doens't accept subclasses, therefore this will always return false.  Make sure to always add tests cases when delegating into `super.equals` as an implicit dependency to the super class policy regarding subclasses is created. Need some kind of safeguard to make sure that a change in the base class doesn't generate a behavior change here

2021-04-28 15:34 UTC, marianogonzalez commented on src/main/java/org/mule/runtime/api/meta/model/parameter/FieldValueProviderModel.java
> +    return new EqualsBuilder()
use `Objects.equals()` instead

2021-04-28 15:34 UTC, marianogonzalez commented on src/main/java/org/mule/runtime/api/meta/model/parameter/ValueProviderModel.java
> -public final class ValueProviderModel {
add `@NoExtend` then

2021-04-28 15:34 UTC, marianogonzalez commented on src/main/java/org/mule/runtime/api/value/ValueProviderService.java
> +  ValueResult getFieldValues(Location location, String parameter, String targetPath);
doesn't this require a `default` impl in order to not break backwards compatibility? surprised that revApi didn't pick this up as an issue

2021-04-28 16:09 UTC, ndinu commented on src/main/java/org/mule/runtime/api/value/ValueProviderService.java
> +  ValueResult getFieldValues(Location location, String parameter, String targetPath);
I think that this has to do with the fact that the interface is annotated with @NoImplement.

2021-05-05 18:28 UTC, ndinu approved these changes

2021-05-10 15:38 UTC, marianogonzalez approved these changes

2021-05-10 15:39 UTC, merged