MULE-19388: ValueProviderModels from sdk-api usages must provide a SinceMuleVersionModelProperty
mulesoft/mule-api pull request #822
Opened 2021-05-05 15:58 UTC by ndinu

2021-05-05 17:05 UTC, marianogonzalez requested changes

2021-05-05 17:05 UTC, marianogonzalez commented on src/main/java/org/mule/runtime/api/meta/model/parameter/ValueProviderModel.java
> +    return unmodifiableSet(new LinkedHashSet<>(modelProperties.values()));
don't copy on each invocation. Create the copy and the unmodifiable wrapper at the constructor itself

2021-05-05 17:05 UTC, marianogonzalez commented on src/main/java/org/mule/runtime/api/meta/model/parameter/ValueProviderModel.java
> +        Arrays.stream(modelProperties).collect(toMap(modelProperty -> modelProperty.getClass(), modelProperty -> modelProperty));
static import

2021-05-06 13:55 UTC, marianogonzalez requested changes

2021-05-06 13:55 UTC, marianogonzalez commented on src/main/java/org/mule/runtime/api/meta/model/parameter/ValueProviderModel.java
> +    if (modelPropertiesValues == null) {
why the null check? this condition should be impossible

2021-05-06 14:32 UTC, ndinu commented on src/main/java/org/mule/runtime/api/meta/model/parameter/ValueProviderModel.java
> +    if (modelPropertiesValues == null) {
If this is deserialized, wouldn't the modelPropertiesValues be null?

2021-05-06 14:42 UTC, marianogonzalez commented on src/main/java/org/mule/runtime/api/meta/model/parameter/ValueProviderModel.java
> +    if (modelPropertiesValues == null) {
that depends on the type adapter impl, but get your point

2021-05-06 14:42 UTC, marianogonzalez submitted a review, later dismissed

2021-05-13 15:59 UTC, SebaElizalde approved these changes

2021-05-13 16:01 UTC, merged