Feature/mule 19588 only api
mulesoft/mule-api pull request #838
Opened 2021-07-16 23:39 UTC by fsgonz

2021-07-19 14:46 UTC, elrodro83 submitted a review, later dismissed

2021-07-19 17:01 UTC, elrodro83 requested changes
It is hard to understand what a client code should by just reading the javadocs, they should be more explanatory.

2021-07-19 17:01 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/profiling/notification/ProfilingNotification.java
> +public class ProfilingNotification extends AbstractServerNotification {
wasn;t the general idea to hide the actual notification framework used under the hood?

2021-07-19 17:01 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/profiling/type/ProfilingEventType.java
> + */
`@since 1.4`

2021-07-19 17:01 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/profiling/type/ProfilingEventType.java
> +  String getProfilingEventName();
wouldn't this better be an enum instead of a Stirng?

2021-07-19 17:07 UTC, fsgonz commented on src/main/java/org/mule/runtime/api/profiling/ProfilerDataConsumerDiscoveryStrategy.java
> +public interface ProfilerDataConsumerDiscoveryStrategy {
Not by the developer of data consumers. But it is possible that in the future different environments wants to create their own discoveries strategies (for example CH).

2021-07-19 17:28 UTC, fsgonz commented on src/main/java/org/mule/runtime/api/profiling/type/ProfilingEventType.java
> +  String getProfilingEventName();
Eventually other components apart from the runtime (connectors, sdk, services) will be able to produce profiling data and they should be able to register their own types without modifying the API (for example adding one more enum item).

2021-07-19 20:32 UTC, elrodro83 requested changes

2021-07-19 20:32 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/profiling/ProfilerDataConsumerDiscoveryStrategy.java
> +public interface ProfilerDataConsumerDiscoveryStrategy {
So this shouldn't have `@NoImplement` and must miantain backwards compatibility with the implementors. Also, these usages you mention must be added to the javadoc

2021-07-19 20:32 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/profiling/type/ProfilingEventType.java
> +  String getProfilingEventName();
an interface then? the one for the rutime can be an enum in that case

2021-07-19 22:33 UTC, fsgonz commented on src/main/java/org/mule/runtime/api/profiling/type/ProfilingEventType.java
> +  String getProfilingEventName();
The interface is ProfilingEventType. I've added more methods to the interface to offer more information regarding the profiling event type.

2021-07-20 12:45 UTC, elrodro83 requested changes

2021-07-20 12:45 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/profiling/ProfilerDataConsumerDiscoveryStrategy.java
> + * Different environments can use different discoveries strategies (CH may use a different strategy).
`discoveries` -> `discovery`

2021-07-20 12:45 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/profiling/ProfilerDataConsumerDiscoveryStrategy.java
> + * Different environments can use different discoveries strategies (CH may use a different strategy).
remove ` (CH may use a different strategy)` (don't mention CH in CE code)

2021-07-20 12:45 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/profiling/ProfilingDataConsumer.java
> + * The implementation of this interface will be discovered by the Mule Runtime. Every time a profiling event included in the
add `through a {@link ProfilerDataConsumerDiscoveryStrategy}` after `discovered by the Mule Runtime` ? Relating these interfaces ion the docs hepls understand how the different pieces interact with each other.

2021-07-20 12:45 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/profiling/ProfilingDataProducer.java
> +  void event(T profilerEventContext);
add a verb to the method name. e.g: `triggerEvent`

2021-07-20 12:45 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/profiling/ProfilingEventContext.java
> +  long getTimestamp();
rename to `eventTriggerTimestamp`?

2021-07-20 12:45 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/profiling/ProfilingService.java
> + * and register a {@link ProfilingEventContext} or obtain a {@link ProfilingDataProducer} to begin emitting profiling data. For
`for example` -> `for instance`

2021-07-20 12:45 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/profiling/type/ProfilingEventType.java
> + * A component (a connector, the Runtime itself) may register this profiling event type by invoking
is this list exhaustive (`a connector, the Runtime itself`)? Can this be used by code of the environment (CH) or an app?

2021-07-20 12:45 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/profiling/type/ProfilingEventType.java
> +  String getProfilerEventTypeNamespace();
provide examples of the namespace, or how to determine it. Refer to `ErrorType` that has a similar concept.

2021-07-20 12:45 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/profiling/type/ProfilingEventType.java
> +  long getProfilingEventTypeId();
What is the point of this id having the =namespace/name already?

2021-07-20 13:32 UTC, fsgonz commented on src/main/java/org/mule/runtime/api/profiling/type/ProfilingEventType.java
> + * A component (a connector, the Runtime itself) may register this profiling event type by invoking
Removed most of this. There is @see to ProfilingService to know the specifics of the injection/registration mechanism.

2021-07-20 15:00 UTC, elrodro83 submitted a review, later dismissed

2021-07-20 16:52 UTC, elrodro83 approved these changes

2021-07-20 19:22 UTC, elrodro83 approved these changes

2021-07-20 19:38 UTC, fsgonz commented
--validate

2021-07-20 20:56 UTC, fsgonz commented
--validate

2021-07-21 14:12 UTC, merged