Feature/ee 7726 v2
mulesoft/mule-api pull request #848
Opened 2021-07-26 15:50 UTC by fsgonz

2021-07-26 15:53 UTC, IvanAndresFritzler submitted a review, later dismissed

2021-07-26 16:54 UTC, elrodro83 submitted a review, later dismissed

2021-07-27 13:46 UTC, fsgonz commented
We'll add more tests.

2021-07-28 22:02 UTC, elrodro83 requested changes

2021-07-28 22:02 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/profiling/type/ProcessingStrategyProfilingEventType.java
> +public class ProcessingStrategyProfilingEventType implements ProfilingEventType<ProcessingStrategyProfilingEventContext> {
will users of this class need to instantiate/extend this? If not, add the annotations indicating this (and/or make it final)

2021-07-28 22:02 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/profiling/type/ProcessingStrategyProfilingEventType.java
> + * A {@link ProfilingEventType} for processing strategies.
Add some explanation of how this class must be used (or link to the type where this is already docuemnted)

2021-07-28 22:02 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/profiling/type/RuntimeProfilingEventType.java
> +public class RuntimeProfilingEventType {
will users of this class need to instantiate/extend this? If not, add the annotations indicating this (and/or make it final)

2021-07-28 22:02 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/profiling/type/RuntimeProfilingEventType.java
> + * {@link ProfilingEventType}'s associated to the Runtime {@link ProfilingEventType}'s.
Add some explanation of how this class must be used (or link to the type where this is already docuemnted)

2021-07-28 22:02 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/profiling/type/RuntimeProfilingEventType.java
> +  private static final String CORE_NAMESPACE = "CORE";
isn't MULE namespace better?

2021-07-28 22:02 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/profiling/type/RuntimeProfilingEventType.java
> +   * @since 4.4
the since here in the fiuelds areredundant, this is already at the class level

2021-07-28 22:02 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/profiling/type/context/ProcessingStrategyProfilingEventContext.java
> +public interface ProcessingStrategyProfilingEventContext extends ProfilingEventContext {
usage/annotations

2021-07-29 00:51 UTC, fsgonz commented on src/main/java/org/mule/runtime/api/profiling/type/RuntimeProfilingEventType.java
> +public class RuntimeProfilingEventType {
we set this to final. But this class involves a list of profiling event types. Renamed to RuntimeProfilingEventTypes.

2021-07-29 00:51 UTC, fsgonz commented on src/main/java/org/mule/runtime/api/profiling/type/RuntimeProfilingEventType.java
> + * {@link ProfilingEventType}'s associated to the Runtime {@link ProfilingEventType}'s.
Explanation in each type.

2021-07-29 01:01 UTC, fsgonz commented on src/main/java/org/mule/runtime/api/profiling/type/RuntimeProfilingEventType.java
> +  private static final String CORE_NAMESPACE = "CORE";
Ok.

2021-07-29 13:11 UTC, elrodro83 approved these changes

2021-07-29 16:08 UTC, merged