MULE-19496: Feature flags documentation is not complete
mulesoft/mule-api pull request #856
Opened 2021-08-04 16:27 UTC by IvanAndresFritzler

2021-08-05 19:24 UTC, eze210 commented
--validate

2021-08-06 19:44 UTC, elrodro83 requested changes

2021-08-06 19:44 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/config/MuleRuntimeFeature.java
> + * meaningful, client oriented name, and must provide values for all the {@link Feature} fields.
`client oriented ` -> `customer facing`

2021-08-06 19:44 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/config/MuleRuntimeFeature.java
> +   * When enabled, DataWeave will correctly handle split exceptions, avoiding some serialization issues. For more information, see
Aren't all the `For mor einformation...` sentencies redundant, since the issue is already aprt of the feature?

2021-08-06 19:44 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/config/MuleRuntimeFeature.java
> +   * When enabled, DataWeave will correctly handle split exceptions, avoiding some serialization issues. For more information, see
make shure that these messages modificaitons are reviewed by whoever added them as well

2021-08-11 05:27 UTC, IvanAndresFritzler commented on src/main/java/org/mule/runtime/api/config/MuleRuntimeFeature.java
> +   * When enabled, DataWeave will correctly handle split exceptions, avoiding some serialization issues. For more information, see
Reverted to "splitter" in order to align the description with the fix release notes (you can check them in https://docs.mulesoft.com/release-notes/mule-runtime/mule-4.3.0-release-notes by searching "SE-19157". Now this brings up another inconsistency: The Ticket ID that we use in the feature flags (MULE/DW/...) does not match with the one that we use in the release notes (SE). This will be addressed in another task, because implies release notes modifications.

2021-08-11 12:09 UTC, elrodro83 approved these changes

2021-08-11 12:12 UTC, merged