MULE-19596: Implement a profiling data consumer discovery strategy ba…
mulesoft/mule-api pull request #867
Opened 2021-09-01 05:25 UTC by IvanAndresFritzler

…sed on server plugins

2021-09-01 21:17 UTC, fsgonz requested changes

2021-09-01 21:17 UTC, fsgonz commented on api-changes.json
> +          "justification": "Experimental API"
use the actual justification for the change, not the reason why the change may be allowed.

2021-09-01 21:17 UTC, fsgonz commented on api-changes.json
> +          "justification": "Experimental API"
use the actual justification for the change, not the reason why the change may be allowed.

2021-09-01 21:17 UTC, fsgonz commented on api-changes.json
> +          "justification": "Experimental API"
use the actual justification for the change, not the reason why the change may be allowed.

2021-09-02 13:27 UTC, elrodro83 approved these changes

2021-09-02 16:20 UTC, fsgonz approved these changes

2021-09-02 16:24 UTC, merged