MULE-19815: load components with composite classloader
mulesoft/mule-api pull request #892
Opened 2021-10-01 19:16 UTC by jcgrethe

2021-10-01 19:38 UTC, jcgrethe commented
--validate

2021-10-04 15:22 UTC, elrodro83 requested changes

2021-10-04 15:22 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/config/MuleRuntimeFeature.java
> +      "When enabled, extensions will be loaded with an artifact classloader.",
replace `an artifact classloader` by a more concrete definition of what artifact's classloader will be used. Remember that artifact may refer to an app, a domain, a plugin, a policy... so this wording is too ambiguous

2021-10-04 18:43 UTC, elrodro83 approved these changes

2021-10-04 18:48 UTC, merged