W-11147961: Error Mapping not working while deploying Header Injectio…
mulesoft/mule-api pull request #998
Opened 2022-06-28 19:40 UTC by sofiamorseletto

…n custom policy

2022-06-29 11:51 UTC, sofiamorseletto commented
--validate

2022-06-29 12:04 UTC, elrodro83 requested changes

2022-06-29 12:04 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/util/MuleSystemProperties.java
> +      SYSTEM_PROPERTY_PREFIX + "applyOperationErrorMappings";
the name of the property should mention `operationPolicies` somehow

2022-06-29 12:04 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/util/MuleSystemProperties.java
> +   * When set to true, if an error is thrown in a processor inside a policy, the policy's error resolution is ignored so that the
this would affect the error generated by an operation policy as a whole, not tied to a particular processor within the policy. Also make clear that this happens only with operationPolicies, not with sourcePolicies.

2022-06-29 12:04 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/util/MuleSystemProperties.java
> +   * processor's error mappings are applied successfully (W-11147961)
`processor's error mappings ` -> `processor on which the policy was applied`

2022-06-29 12:04 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/util/MuleSystemProperties.java
> +   * processor's error mappings are applied successfully (W-11147961)
don't think we need to mention the ticket here, it is already mentioned in the FF

2022-06-29 12:04 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/config/MuleRuntimeFeature.java
> +      "W-11147961", "4.5.0", APPLY_OPERATION_ERROR_MAPPINGS_PROPERTY);
See comments on the systemProperty

2022-06-29 18:51 UTC, elrodro83 requested changes

2022-06-29 18:51 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/config/MuleRuntimeFeature.java
> +  APPLY_OPERATION_ERROR_MAPPINGS_WHEN_INSIDE_OPERATION_POLICY(
rename to `HONOR_ERROR_MAPPINGS_WHEN_POLICY_APPLIED_ON_OPERATION`

2022-06-29 18:51 UTC, elrodro83 commented on src/main/java/org/mule/runtime/api/util/MuleSystemProperties.java
> +      SYSTEM_PROPERTY_PREFIX + "applyOperationErrorMappingsWhenInsideOperationPolicy";
rename accordingly to prev comment

2022-06-30 13:33 UTC, elrodro83 approved these changes

2022-06-30 14:13 UTC, sofiamorseletto commented
--validate

2022-06-30 15:56 UTC, merged